# Generated by Django 3.1 on 2022-02-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220217_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='text',
        ),
    ]
