# Generated by Django 3.1 on 2022-02-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220218_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='email',
        ),
    ]
