# Generated by Django 3.1 on 2022-02-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220218_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='email',
        ),
    ]
